remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Juanmi Taboada
description: General information and a few things I have been doing recently

show_downloads: false
google_analytics: G-8KST6F5VX7
